/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_APITest */

#ifndef _Included_com_jni_APITest
#define _Included_com_jni_APITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_APITest
 * Method:    APICaller
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_APITest_APICaller
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
